### ISSUE TITLE
add elements dynamically 

### ISSUE THREAD

**Issue by JasonHuangHuster** [jmurty/java-xmlbuilder#14]
i gotta generate xml elements from a list , for example ：

```
<params>
       <param>1<param/>
       <param>1<param/>
       <param>1<param/>
</params>
```

the number <param> element inside the <params> is variable  . so i wrote the code in this way ：
```
 builder.elem("params");
for (Param param : paramList) {
	builder.elem("param")
	.attribute("name", param.getName())
	.attribute("key", param.getKey())
	.attribute("type", param.getType())
	.attribute("desc", param.getType())
	.attribute("defaultValue", param.getDefaultValue());
}
```

              
the result turns out ：

```
<params/>
<param defaultValue="213" desc="4231" key="321" name="321" type="4231"/>
```

is there any solution to this ?  
BTW , xmlbuilder is really helpful .. keep the good working please :+1:

**Comment by JasonHuangHuster** [comment]
i figured out it  by myself , i was thinking deleting this issue , but i think it might be helpful for others . 
```
XMLBuilder2 params = builder.element("params");
for (Param param : paramList) {
	params.element("param")
	.attribute("name", param.getName())
	.attribute("key", param.getKey())
	.attribute("type", param.getType())
	.attribute("desc", param.getType())
	.attribute("defaultValue", param.getDefaultValue());
}
```
stop using the chain method way , and it worked .

**Comment by jmurty** [comment]
Thanks for following up. 

You are right: to add new elements under a parent element, you need to call the `element()` method on the parent's builder instance.
