### ISSUE TITLE
how to generate xml start tag ?

### ISSUE THREAD

**Issue by JasonHuangHuster** [jmurty/java-xmlbuilder#15]
`<?xml version="1.0" encoding="UTF-8"?>`

how to generate this tag ... i tried every way but all output begins with the root element . help needed ..  :(

**Comment by jmurty** [comment]
The XML declaration header is included or not based on the output properties you are using, and possibly the default output properties of your system. See the documentation about this here: https://github.com/jmurty/java-xmlbuilder#output

If your system omits the XML declaration header by default, you should be able to fix this by providing something like the following output property:
`
outputProperties.put(javax.xml.transform.OutputKeys.OMIT_XML_DECLARATION, "no");
`

**Comment by JasonHuangHuster** [comment]
sorry for the miss reading ...    `xmlbuilder` is brilliant  in everyway . tons of thanks for your great work :+1:
