### ISSUE TITLE
which java version should java-xmlbuilder support for on default?

### ISSUE THREAD

**Issue by harkue** [jmurty/java-xmlbuilder#18]
which java version should java-xmlbuilder support for?

Under the pom.xml on master branch:
 - 1.6:  will cause a error like ``Unsupported major.minor version 51.0``
 - 7: ok
 - 8: ok
 - [9-13]:  ``Failed``, default maven source plugin suggest use java version 1.6 or later

when I add this in `pom.xml`:
```xml
<properties>
    <maven.compiler.source>1.6</maven.compiler.source>
    <maven.compiler.target>1.6</maven.compiler.target>
</properties>
```
The compile result is as belowing:
 - 1.6:  will cause a error like ``Unsupported major.minor version 51.0``
 - 7: ok
 - 8: ok
 - 9, 10:  ok
 - [11-13]: ``Failed``, default maven source plugin suggest use java version 7 or later

Then I change this to 1.8 in `pom.xml`:
```xml
<properties>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
</properties>
```
 - 8: ok
 - 9, 10:  ok
 - [11-13]: ``Failed``, `javax.annotation` had been removed since java 11

So in this way, which version range should java-xmlbuilder support for?

**Comment by jmurty** [comment]
Hi @harkue I have done some digging and made some tweaks, so I think the latest code now on `master` will work for recent Java versions.

The codebase is largely unchanged since 2014, and was last deployed to Maven in 2017, and the Java ecosystem has moved on since then.

Can you please confirm that you can build with the latest `pom.xml` which now has source & target set to `1.7` along with many other tweaks that were needed to make things work with Java 12?

**Comment by harkue** [comment]
Hi, @jmurty Thanks for your reply.
I am trying to build a Github Action to trigger CI on push or PR event, and working on find a way to compatible with most Java versions.

**Comment by jmurty** [comment]
Automated tests and code coverage reports would be great, though to be honest this project barely gets any pushes or PRs nowadays.

But I encourage you to experiment with this if you like.

I just updated the project to build with source version `1.7` so tests against all Java versions from 7 onwards would be great. I barely use Java myself now so I have lost track of the active versions that exist, but I guess the project should support 7, 8, 10, 11, & 12?

**Comment by jmurty** [comment]
Look at the matrix strategy for GitHub Actions for a way to run tests across multiple versions: https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix

I have used this [in another project](https://github.com/elasticdog/transcrypt/blob/master/.github/workflows/run-bats-core-tests.yml) to run tests on multiple OSes, but the links in the GitHub docs should give hints on how to do this for multiple versions of Java instead.
