### ISSUE TITLE
How to create sibling elements with text

### ISSUE THREAD

**Issue by BeeDance** [jmurty/java-xmlbuilder#20]
i want create xml like below, but when do like that it return error.
`        Date date = new Date();
        XMLBuilder2 builder = XMLBuilder2.create("Project")
                .e("DATE").t(new SimpleDateFormat("MM/dd/yyyy").format(date))
                .e("TIME").t(new SimpleDateFormat("HH:mm:ss").format(date)) `

![image](https://user-images.githubusercontent.com/6102853/87509050-4f434900-c6a3-11ea-95e5-1064b3c1b033.png)
![image](https://user-images.githubusercontent.com/6102853/87509167-98939880-c6a3-11ea-8f0d-bacdc9d455b5.png)
![image](https://user-images.githubusercontent.com/6102853/87509202-ac3eff00-c6a3-11ea-859f-1f318dc356d3.png)

**Comment by jmurty** [comment]
Hi @BeeDance when you create a new element with `XMLBuilder2` any following method calls are made on that element, so calling `.e("DATE").e("TIME")` would actually produce `<DATE><TIME/></DATE>` which isn't what you want even ignoring the fact you can't create child elements after you add text.

What you want to do is create sibling elements, and to do this you must go back "up" to the parent after creating an element before creating the next one. You go up with the `up()` method.

For your example, you will need something like the following (note the `.up()` method call between elements):
```java
XMLBuilder2.create("Project")
  .e("DATE").t(myDateText)
  .up()  // Go back up to parent <Project> element
  .e("TIME").t(myTimeText);
```

**Comment by BeeDance** [comment]
@jmurty thanks, it's worked.
