### ISSUE TITLE
How to add text and elements in parallel

### ISSUE THREAD

**Issue by xulihang** [jmurty/java-xmlbuilder#21]
I want to build this sample xliff xml:

```xml
<g1>Styles like <g2>bold</g> is supported.</g>
```
I was trying with this code:

```java
builder.e("g1")
            .t("Styles like ")
            .e("g2")
                .t("bold")
            .up()
            .t("is supported")
```

But I got this error: `java.lang.IllegalStateException: Cannot add sub-element to element <g> that already contains the Text node:`

**Comment by jmurty** [comment]
Hi, java-xmlbuilder doesn't support adding multiple text nodes to an element. That's an unusual use-case for most XML so I never thought to make it possible. 

You should be able to do this by getting the underlying node and working with it directly. But at that point the builder isn't helping you. 

If you are interested in adding support for doing this I encourage pull requests. Maybe add something like a `.text(text, appendToExisting)` method with an extra Boolean flag to permit adding multiple text nodes.

**Comment by xulihang** [comment]
Hi,

I decided to use the raw javax.xml.parsers.DocumentBuilder directly.
