### ISSUE TITLE
builder.asString(outputProperties) on existing XML file adds additional newline

### ISSUE THREAD

**Issue by hegdemk2004** [jmurty/java-xmlbuilder#23]
Hi, Thanks for a simple framework ad beginner can also use. I followed the example provided in the Readme and found a minor issue. After creating the Projects.xml, Reading it back and Adding additional element <Location2 type="Testing"/>, I wanted to write the updated XML back to file with proper indentation as before. 

However the builder.asString(outputProperties) after the update, adds additional blank lines between each line of XML I think   if I read, update and write (with outputProerties) an XML file multiple times, each time it will add additional blank lines. Is there a quick fix or workaround for this issue please? Thanks.

**Comment by jmurty** [comment]
Hi @hegdemk2004 can you share your code where you are seeing this problem with excess whitespace?

I haven't been able to reproduce the issue myself with code like the following that writes and re-reads the same XML content to three files. My second and third files don't have extra blank lines.
```java
Properties outputProperties = new Properties();
outputProperties.put(javax.xml.transform.OutputKeys.INDENT, "yes");
outputProperties.put("{http://xml.apache.org/xslt}indent-amount", "2");

XMLBuilder2 builder = XMLBuilder2.parse(EXAMPLE_XML_DOC);
builder.element("NewElement1");
File out1 = new File("/tmp/out1.xml");
builder.toWriter(new FileWriter(out1), outputProperties);

builder = XMLBuilder2.parse(out1);
builder.element("NewElement2");
File out2 = new File("/tmp/out2.xml");
builder.toWriter(new FileWriter(out2), outputProperties);

builder = XMLBuilder2.parse(out2);
builder.element("NewElement3");
File out3 = new File("/tmp/out3.xml");
builder.toWriter(new FileWriter(out3), outputProperties);
```

**Comment by hegdemk2004** [comment]
Hi James,
Thanks for the quick response. 

    On Friday, February 12, 2021, 5:14:56 PM GMT+5:30, James Murty <notifications@github.com> wrote:  
 I dont think the coding captures the scenario, I mentioned correctly.
I have tested it again and again.. The issue is that the when you persist the formatted file it will have New Line character added - of course for formatting. Later in say second step I want to edit the file, when I read the file from disk the New Line is preserved. So after adding new element if I format and persist again the second time re-formatting will add another new line (again for formatting).

The solution I have found is to remove the New Line between tags upon loading, then editing and persisting the edited file with formatting. 

If you use the following code you should be able to reproduce the issue. I believe its an inherent issue in the DOM formatting and loading.
Properties outputProperties = new Properties();
outputProperties.put(javax.xml.transform.OutputKeys.INDENT, "yes");
outputProperties.put("{http://xml.apache.org/xslt}indent-amount", "2");

XMLBuilder2 builder = XMLBuilder2.parse(EXAMPLE_XML_DOC);
builder.element("NewElement1");
File out1 = new File("/tmp/out1.xml");
builder.toWriter(new FileWriter(out1), outputProperties);
 out1 = new File("/tmp/out1.xml"); //Re-read the formatted and persisted file from disk (NOT THE IN-memory version)

builder = XMLBuilder2.parse(out1);
builder.element("NewElement2");File out2 = new File("/tmp/out2.xml");builder.toWriter(new FileWriter(out2), outputProperties);Regards,Mahesh
 


Hi @hegdemk2004 can you share your code where you are seeing this problem with excess whitespace?

I haven't been able to reproduce the issue myself with code like the following that writes and re-reads the same XML content to three files. My second and third files don't have extra blank lines.
Properties outputProperties = new Properties();
outputProperties.put(javax.xml.transform.OutputKeys.INDENT, "yes");
outputProperties.put("{http://xml.apache.org/xslt}indent-amount", "2");

XMLBuilder2 builder = XMLBuilder2.parse(EXAMPLE_XML_DOC);
builder.element("NewElement1");
File out1 = new File("/tmp/out1.xml");
builder.toWriter(new FileWriter(out1), outputProperties);
 out1 = new File("/tmp/out1.xml"); //Re-read the formatted and persisted file
builder = XMLBuilder2.parse(out1);
builder.element("NewElement2");File out2 = new File("/tmp/out2.xml");builder.toWriter(new FileWriter(out2), outputProperties);builder = XMLBuilder2.parse(out2);builder.element("NewElement3");File out3 = new File("/tmp/out3.xml");builder.toWriter(new FileWriter(out3), outputProperties);

**Comment by jmurty** [comment]
Hi, I still cannot reproduce the issue as described in MacOS. Perhaps there is some difference in our systems that prevents the extra whitespace for me but not you?

In any case, it sounds like you have found a solution to remove the newlines. The builder objects also have a method for doing this kind of clean-up, the `stripWhitespaceOnlyTextNodes()` method removes text nodes that contain nothing but whitespace.
